import { SignIn, SignedIn, SignedOut, UserButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { user } = useUser();

  const { data } = api.posts.getAll.useQuery();

  const styles = {
    backgroundColor: "#002fff",
    backgroundImage: "radial-gradient(at 17% 30%, #cc66ff 0, transparent 73%), radial-gradient(at 14% 95%, #2563eb 0, transparent 26%), radial-gradient(at 60% 26%, #3721b6 0, transparent 37%), radial-gradient(at 33% 87%, rgb(207, hsl(336.79245283018867, 52.475247524752476%, 60.3921568627451%)parent 54%), radial-gradient(at 32% 65%, #6fabff 0, transparent 44%), radial-gradient(at 53% 68%, #a0c0ff 0, transparent 26%)",
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center" style={styles}>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-bold text-white">HOE<span className="text-[#cc66ff]">4</span>HILA</h1>
          <SignedOut>
            <SignIn />
          </SignedOut>
          <SignedIn>
            <div>
              <span><UserButton /></span>
              <span>{user?.username}!</span>
            </div>
            <div>
              {data?.map(({ id, content }) => (<div key={id}>{content}</div>))}
            </div>
          </SignedIn>
        </div>
      </main>
    </>
  );
};

export default Home;
