import { SignIn, SignedIn, SignedOut, UserButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { use } from "react";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const { user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>hoe4hila</h1>
          <SignedOut>
            <SignIn />
          </SignedOut>
          <SignedIn>
            <div>
              <span><UserButton /></span>
              <span>{user?.username}!</span>
            </div>
          </SignedIn>
        </div>
      </main>
    </>
  );
};

export default Home;
